jo/urls.py
from django.contrib import admin
from django.urls import include, path
from shop import views
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('orders/', include('orders.urls')),
    path('carts/', include('cart.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^accounts/', include('django_registration.backends.activation.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),

] \
 \
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('orders/', views.view, name='orders'),
    path('orders-cart/<int:id>/', views.viewCart, name='orderCart'),
    path('del/<int:id>/', views.delO, name='del'),

]

cart/models.py
from django.db import models
from shop.models import Product


class Cart(models.Model):
    order_id = models.CharField(max_length=100,default=0)
    total = models.DecimalField(max_digits=100, decimal_places=0, default=0)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        return "Cart id: %s" % (self.id)


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, null=True, blank=True, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, )
    line_total = models.DecimalField(default=10, max_digits=100, decimal_places=0)
    quantity = models.IntegerField(default=1)
    created = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        try:
            return str(self.cart.id)
        except:
            return self.product.name

orders/models.py
from django.db import models
from shop.models import Product
from cart.models import Cart

STATUS_CHOICE = (
    ('Обзвон', 'Обзвон'),
    ("пох", "пох"),
    ("finished","finished")

)


class Order(models.Model):
    order_id = models.CharField(max_length=120, default='abc', unique=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE,blank=True, default=None, )
    costumer_name = models.CharField(verbose_name="Название", max_length=20, default='')
    costumer_phone = models.CharField(verbose_name='Номер тел.', null=True, max_length=20, )
    comments = models.TextField(verbose_name='Пожелание', null=True)
    status = models.CharField(max_length=120, choices=STATUS_CHOICE, default="Обзвон")
    created = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    class Meta:
        verbose_name = "Заказ",
        verbose_name_plural = "Заказы"



orders/forms.py
from django import forms
from .models import *

orders/views.py
import time

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import *
from django.urls import reverse
from django.shortcuts import redirect

def checkout(request):
    name = request.POST.get('name')
    phone = request.POST.get('phone')
    com = request.POST.get('description')
    try:
        the_id = request.session['cart_id']
        cart = Cart.objects.get(id=the_id)
    except:
        the_id = None
        return HttpResponseRedirect(reverse("cart"))

    new_order, created = Order.objects.get_or_create(cart=cart)
    if created:
        new_order.order_id = cart.order_id
        new_order.costumer_name = name
        new_order.costumer_phone = phone
        new_order.comments = com
        new_order.save()

    if new_order.status == "finished":
        return HttpResponseRedirect(reverse('cart'))

    request.session.modified = True

    del request.session['cart_id']
    del request.session['items_total']

    return render(request, 'index.html')


def view(request):
    orders = Order.objects.all()

    return render(request, 'orders/orders.html', locals())


def viewCart(request, id):
    cart = Cart.objects.get(id=id)

    return render(request, 'orders/order_cart.html', locals())


def delO(request, id):
    cart = Cart.objects.get(id=id)
    cart.delete()
    return HttpResponseRedirect(reverse('orders'))

templates/orders/order_cart.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}

    <div class="container-fluid">
        <div class="row clearfix">
            <div class="offset-1 col-lg-10">
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane in active" id="details" aria-expanded="true">
                        <div class="card" id="details">
                            <div class="body">
                                <div class="mt-40"></div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="table-responsive">
                                            <table class="table table-hover">
                                                <thead>
                                                <tr>
                                                    <th>#</th>
                                                    <th width="60px">Наименование</th>
                                                    <th></th>
                                                    <th class="hidden-sm-down">Описание</th>
                                                    <th>Количество</th>
                                                    <th class="hidden-sm-down">Unit Cost</th>
                                                    <th>Сумма</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                        {% for item in cart.cartitem_set.all %}

                                                            <tr>
                                                                <td>4</td>
                                                                <td><img src="assets/images/ecommerce/4.png" width="40"
                                                                         alt="Product img"></td>
                                                                <td>{{ item.product }}</td>
                                                                <td class="hidden-sm-down">Contrary to popular belief,
                                                                    not
                                                                    simply random text
                                                                </td>
                                                                <td>{{ item.quantity }}</td>


                                                                <td class="hidden-sm-down">
                                                                    <form class="form pull-right" method="get"
                                                                          action="{% url "update_to_cart" item.product.slug %}">

                                                                        <input name="qty" type="number">
                                                                        <input type="submit" value="add">

                                                                    </form>
                                                                </td>
                                                                <td>{{ item.product.price }}</td>
                                                                <td>
                                                                    <a href='{% url "remove" item.id %}'
                                                                       class="btn btn-delete "><i
                                                                            class="zmdi zmdi-shopping-cart"></i></a>
                                                                </td>
                                                            </tr>

                                                        {% endfor %}


                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-md-6">
                                        <h3 class="m-b-0 m-t-10">Сумма заказа:{{ cart.total }}</h3>

                                    </div>

                                </div>
                            </div>

                        </div>
                    </div>

                </div>

            </div>

        </div>

    </div>

{% endblock %}

templates/orders/orders.html
<!doctype html>
<html class="no-js " lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta name="description" content="Responsive Bootstrap 4 and web Application ui kit.">
    <title>:: Oreo Bootstrap4 Admin ::</title>
    <link rel="icon" href="favicon.ico" type="image/x-icon"> <!-- Favicon-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/footable.standalone.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/footable.bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/color_skins.css' %}">
    <!-- Custom Css -->

</head>
<body class="theme-purple">
<div class="container-fluid">

    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="card">

                <div class="body table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                             <th>Ссылка</th>
                            <th>Имя</th>
                            <th>Номер телефона</th>
                            <th>Дата</th>
                            <th>Номер заказа</th>
                            <th>Статус</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for order in orders %}
                            <tr>
                            <td><a href="{% url 'orderCart' order.cart_id %}">Корзина</a></td>
                                <td>{{ order.costumer_name }}</td>
                                <td>{{ order.costumer_phone }}</td>
                                <td>{{ order.created }}</td>
                                <td>{{ order.order_id }}</td>
                                <td>
                                    <ul class="nav nav-tabs">
                                        {% if order.status == "Новая" %}
                                        <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#home"
                                                                aria-expanded="true">Новая</a></li>
                                            {% else %}
                                              <li class="nav-item"><a class="nav-link " data-toggle="tab" href="#home"
                                                                aria-expanded="true">Новая</a></li>
                                        {% endif %}

                                     {% if order.status == "Отказ" %}
                                         <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#profile"
                                                                aria-expanded="false">Отказ</a></li>
                                            {% else %}
                                               <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#profile"
                                                                aria-expanded="false">Отказ</a></li>
                                        {% endif %}

                                     {% if order.status == "Согласен" %}
                                            <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#messages">Согласен</a>
                                            {% else %}
                                              <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#messages">Согласен</a>
                                        {% endif %}
                                        </li>
                                    </ul>
                                </td>
                                 <td> <a href='{% url "del" order.cart_id %}'
                                                                       class="btn btn-delete "><i
                                                                            class="zmdi zmdi-shopping-cart"></i></a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

</div>
{% block extrahead %}
    <!-- Jquery Core Js -->
    <script type="text/javascript" src="{% static 'js/libscripts.bundle.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendorscripts.bundle.js' %}"></script>


    <script type="text/javascript" src="{% static 'js/footable.bundle.js' %}"></script>


    <script type="text/javascript" src="{% static 'js/mainscripts.bundle.js' %}"></script>


    <script type="text/javascript" src="{% static 'js/footable.js' %}"></script>

{% endblock extrahead %}
</body>
</html>